### ISSUE TITLE
servustv deutchland

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-de-logos#1]
Logo servus tv de

https://presse.servustv.com/

https://presse.servustv.com/Media.aspx

BB MV LokalTV svg

[BB MV LokalTV.zip](https://github.com/Jasmeet181/mediaportal-de-logos/files/3011933/BB.MV.LokalTV.zip)

**Comment by Jasmeet181** [comment]
Thanks Dalmore.

**Comment by dalmore72** [comment]
Thanks
