### ISSUE TITLE
ProSieben HD

### ISSUE THREAD

**Issue by Dimi247TV** [Jasmeet181/mediaportal-de-logos#17]
Hi again, ProSieben HD has since 2015 and WDR 3 since 2016 also a new logo. :D
![ProSieben_HD](https://user-images.githubusercontent.com/122408352/212480508-248158ae-abfc-4e8d-a6e4-2208b7c9da3f.png)
![WDR_3](https://user-images.githubusercontent.com/122408352/212480562-fc36a92a-9c14-424b-a073-ed34d21a3b5b.png)

Greetings
Dimi

**Comment by Jasmeet181** [comment]
Thanks again Dimi.
