### ISSUE TITLE
Logo for "Sky Serien & Shows HD"

### ISSUE THREAD

**Issue by MegaV0lt** [Jasmeet181/mediaportal-de-logos#3]
Can you add a logo for "Sky Serien & Shows HD"? It is a Popupchannel from Sky Deutchlad. It comes from time to time and ist availabel for some days.

**Comment by MegaV0lt** [comment]
Thanks for the add! Super fast and great work...

**Comment by Jasmeet181** [comment]
You're welcome, I don't receive any of these channels so feel free to post any other changes.

**Comment by MegaV0lt** [comment]
Ok, please check
https://github.com/Jasmeet181/mediaportal-de-logos/commit/929a9490d85d3b142f0753ee8d5115ace0bf9d3e#r37744007
at line 3316. There is a typo
