### ISSUE TITLE
Sky Germany (New and renamed channels)

### ISSUE THREAD

**Issue by MegaV0lt** [Jasmeet181/mediaportal-de-logos#4]
Sky Germany (Asstra 19.2°E) has changed there channels of the Cinema packet:

```Sky Cinema				new		Sky Cinema Premieren
Sky Cinema HD			new		Sky Cinema Premieren HD
Sky Cinema +1			ended	
Sky Cinema +1 HD		new		Sky Cinema Thriller HD
Sky Cinema +24			new		Sky Cinema Premieren +24
Sky Cinema +24 HD		new		Sky Cinema Premieren +24 HD
Sky Cinema Hits			new		Sky Cinema Best Of
Sky Cinema Hits HD		new		Sky Cinema Best Of HD
Sky Cinema Emotion		ended	
Sky Cinema Nostalgie		new		Sky Cinema Classics
Sky Cinema Comedy		new		Sky Cinema Fun
```

I did not find logos... ;-(

Look at the last one: https://logos.fandom.com/wiki/Sky_Cinema_Premiere

**Comment by Jasmeet181** [comment]
Some of the users in the MP forum asked for the style of logos in [Sky.de's TV guide](https://www.sky.de/tvguide-7599) for better readability, they're also very easy to replicate compared to the normal Sky logos.

**Comment by MegaV0lt** [comment]
For me the current style is ok.
